---
title: "R Notebook"
output: html_notebook
---

Push the changes to the github
OBS: $ git push -u origin main

Importing libraries
```{r}
library("tidyverse")
library("ggplot2")
library('readxl')

  
cpi = read_excel('raw_data/CPIAUCSL.xls', skip = 10)
interest_rate = read_excel('raw_data/FEDFUNDS.xls', skip = 10)

head(interest_rate)
```

We compute the last 12 months inflation rate
```{r}
# To create the inflation rate in pp%
cpi <- cpi %>%
  mutate(inflation_rate_annual =  (CPIAUCSL/lag(CPIAUCSL, 12)-1)*100 ) %>%
  mutate(change_inflation = (inflation_rate_annual-lag(inflation_rate_annual)))

tail(cpi)
```



```{r}
#Merge both databases
data <- merge(interest_rate, cpi,by="observation_date")

data <- data %>%
  mutate(change_interest_rate = (FEDFUNDS-lag(FEDFUNDS))) 


head(data)
```

```{r}
#library("writexl")
#write_xlsx(data,"merged_data.xlsx")
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.
```{r}
library(ggplot2)

ggplot(data=data, aes(observation_date)) +
  geom_line(aes(y = inflation_rate_annual, colour = "Inflation Rate"))+
  geom_line(aes(y = FEDFUNDS, colour = "Interest Rate"))
```

```{r}
columns <- c('inflation_rate_annual', 'FEDFUNDS')

long_data = stack(data[columns])


library(ggplot2)
ggplot(long_data, aes(x = ind, y = values)) +
  geom_boxplot()
```
```{r}
change_interest_rate = data[c('change_interest_rate')]

increase_interest = change_interest_rate[change_interest_rate>0]
decrease_interest = change_interest_rate[change_interest_rate<0]

increase_df = data.frame(change_interest = increase_interest, label = replicate(length(increase_interest), 'Increase'))

decrease_interest = data.frame(change_interest = abs(decrease_interest), label = replicate(length(decrease_interest), 'Decrease'))

changes_interest = rbind(increase_df, decrease_interest)

ggplot(changes_interest, aes(x = label, y = change_interest)) +
  geom_boxplot()
```


